; Song List
;

    defc    SONG_PI                             =   0
    defc    SONG_PO                             =   1
    defc    SONG_FUNERAL                        =   2
    defc    SONG_SWING                          =   3
    defc    SONG_SWING2                         =   4
    defc    SONG_SWING3                         =   5
    defc    SONG_HITBYPLAYER                    =   6
    defc    SONG_HITBYMONSTER                   =   7
    defc    SONG_KILLMONSTER                    =   8
    defc    SONG_KILLMONSTER2                   =   9
    defc    SONG_LBOLT                          =   10
    defc    SONG_BREATH                         =   11
    defc    SONG_KILLDRAGON                     =   12
    defc    SONG_WALK1                          =   13
    defc    SONG_WALK2                          =   14
    defc    SONG_RUN                            =   15
    defc    SONG_BLOCK                          =   16
